
title: lazy
author: GitHub User
description: > # this means to ignore newlines until "show_exerpts:"
  Hello Friend! Hello Friend?? Weird. 
  I am lazy and I break things! You'll find posts relating to Exploit Development, Reverse Engineering and other security related stuff on this blog. 
  This is mainly my learning space but if you find the posts helpful, then Kudos to you as well! Have fun :)
show_excerpts: false # set to true to show excerpts on the homepage

paginate: 1
paginate_path: "/blog/page:num/"

tag_permalink_style: pretty
tag_page_layout: tag_page
tag_page_dir: tag

# jekyll-dash date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
dash:
  date_format: "%b %-d, %Y"

  disqus:
    shortname: bitbrain-github-io

  # generate social links in footer
  # supported colors: green, red, orange, blue, cyan, pink, teal, yellow, indigo, purple
  social_links:
    - url: https://twitter.com/l42Y_
      icon: twitter-square
      color: cyan
    - url: https://github.com/142y
      icon: github-square
      color: purple

  show_author: true

# Build settings
theme: jekyll-dash

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-paginate
 - liquid-md5
 - jekyll/tagging

# Replaces the default avatar provider (gravatar)
#avatar_source: github
#github_username: bitbrain
